name: Frontend

env:
  SERVER: ftps://marissa.metanet.ch:21/
  USER: kickstart
  REMOTE_ROOT: /

on:
  push:
    branches:
      - master
    paths:
      - "frontend"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npm run build
      - name: Upload build files
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: frontend/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build files
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy to server
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: $SERVER
          ftp-username: $USER
          local-dir: frontend/dist/
          ftp-password: ${{ secrets.FRONTEND_PASSWORD }}
          git-ftp-args: --insecure --remote-root $REMOTE_ROOT
