name: Frontend

env:
  working-directory: ./frontend
  server: ftpes://gutenberg.metanet.ch:21
  # port:
  username: frontendpermaculture
  # remote-root:

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}

      - name: Build project
        run: npm run build
        working-directory: ${{ env.working-directory }}

      - name: Deploy project (FTP)
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ env.server }}
          ftp-username: ${{ env.username }}
          local-dir: frontend/dist/
          ftp-password: ${{ secrets.FRONTEND_PASSWORD }}
          # git-ftp-args: --insecure --remote-root ${{ env.remote-root }}
          git-ftp-args: --insecure

      # https://github.com/easingthemes/ssh-deploy
      # - name: Deploy project (SSH)
      #   uses: easingthemes/ssh-deploy@v2.1.6
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      #     ARGS: "-avzr --delete"
      #     SOURCE: "frontend/dist/"
      #     REMOTE_HOST: ${{ env.server }}
      #     # REMOTE_PORT: ${{ env.port }}
      #     REMOTE_USER: ${{ env.username }}
      #     # TARGET: ${{ env.remote-root }}
