name: Frontend

env:
  working-directory: ./frontend
  server:
  username:
  # remote-root:

on:
  push:
    branches:
      - master
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "10.x"

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.working-directory }}

      - name: Build project
        run: npm run build
        working-directory: ${{ env.working-directory }}

      - name: Deploy project
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: ${{ env.server }}
          ftp-username: ${{ env.username }}
          local-dir: frontend/dist/
          ftp-password: ${{ secrets.FRONTEND_PASSWORD }}
          # git-ftp-args: --insecure --remote-root ${{ env.remote-root }}
          git-ftp-args: --insecure
